// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/_@pinia_nuxt@0.5.5@@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/_nuxtjs-naive-ui@1.0.2@nuxtjs-naive-ui/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/_@formkit_auto-animate@0.8.2@@formkit/auto-animate/nuxt/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/_nuxt@3.14.1592@nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../node_modules/_@pinia-plugin-persistedstate_nuxt@1.2.1@@pinia-plugin-persistedstate/nuxt/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../plugins/APlayer")> &
  InjectionType<typeof import("../../plugins/cherry.js")> &
  InjectionType<typeof import("../../plugins/error")> &
  InjectionType<typeof import("../../plugins/markdown")> &
  InjectionType<typeof import("../../plugins/naive-ui")> &
  InjectionType<typeof import("../../plugins/nprogress")> &
  InjectionType<typeof import("../../plugins/svgIcon")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
